// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Auth0.NancyFx.SelfHost")]
[assembly: AssemblyDescriptionAttribute("Simple Auth0 Provider to use it in self hosted NancyFx Applications")]
[assembly: GuidAttribute("c3568aca-b0f7-4804-a762-352d4272599c")]
[assembly: AssemblyProductAttribute("Auth0.NancyFx.SelfHost")]
[assembly: AssemblyTrademarkAttribute("Copyright ©  devCrowd 2014")]
[assembly: AssemblyVersionAttribute("0.2.1")]
[assembly: AssemblyFileVersionAttribute("0.2.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.1";
    }
}
